name: Add Anime to Favorites

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'Discord User ID'
        required: true
      anime:
        description: 'Anime Title'
        required: true

jobs:
  add-favorite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: إعداد Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: تثبيت requests
        run: pip install requests

      - name: تشغيل سكربت الإضافة
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_ID: ${{ github.event.inputs.user_id }}
          ANIME_TITLE: ${{ github.event.inputs.anime }}
        run: |
          python scripts/add_favorite_action.py
